version: '3.8'

services:
  soulfriends:
    image: mysql:8.0
    container_name: soulfriends_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: soulfriends
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_password
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
