name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [frontend, backend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Verify pnpm Installation
        run: pnpm --version

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm turbo run lint --filter=${{ matrix.package }}

      - name: Test
        run: pnpm turbo run test --filter=${{ matrix.package }}

      - name: Build
        run: pnpm turbo run build --filter=${{ matrix.package }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Verify pnpm Installation
        run: pnpm --version

      - name: Install Dependencies
        run: pnpm install

      - name: Build Frontend and Backend
        run: pnpm build

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          since_last_remote_commit: true
          separator: ","

      - name: Copy Files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: '.'
          target: '/home/${{ secrets.VM_USER }}/app'
          debug: true

      - name: Restart PM2 Processes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
           # install Node.js v18
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # Navigate to the app directory
            cd /home/${{ secrets.VM_USER }}/app

            # Install dependencies with pnpm
            pnpm install --prod

            # Reload pm2 processes
            pm2 reload ecosystem.config.js

            # Check if the frontend app is running and start if necessary
            if ! pm2 list | grep -q 'frontend'; then
              echo "Frontend not running, attempting to start..."
              pm2 start /home/${{ secrets.VM_USER }}/app/apps/frontend/.next/standalone/server.js --name frontend
            fi